### ISSUE TITLE
Importing Goes2Go fails

### ISSUE THREAD

**Issue by isagonza** [blaylockbk/goes2go#32]
Hello!

I installed Goes2Go using pip and I'm trying to follow the example code for downloading and reading the data. When I try to import the module GOES (`from goes2go import GOES`) it returns a syntax error:

  /home/ec2-user/.local/lib/python3.7/site-packages/goes2go/__init__.py:15: UserWarning: goes2go xarray accessors could not be imported.
    warnings.warn("goes2go xarray accessors could not be imported.")
  
  Traceback (most recent call last):
  
    File "/home/ec2-user/.local/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
  
    File "/tmp/ipykernel_19813/3951463100.py", line 1, in <module>
      from goes2go import GOES
  
    File "/home/ec2-user/.local/lib/python3.7/site-packages/goes2go/__init__.py", line 96, in <module>
      from goes2go.NEW import GOES
  
    File "<fstring>", line 1
      (self.satellite=)
                     ^
  SyntaxError: invalid syntax

I tried importing other modules but returns the same error

**Comment by blaylockbk** [comment]
Sorry it's not working for you right now. It looks like you are using Python 3.7. Can you try it with 3.8.
